version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - echo Running tests
      - mvn test
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/GradInfo.jar
  discard-paths: yes

reports:
  JUnitTest-reports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'